package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, POISON, ADD_FRIEND, CONFIRM_FRIEND, ADD_FILE,REMOVE,
	JOINED, ASK_VIEW_FILE, TELL_VIEW_FILE, PING, PONG, BACKUP, UPDATE_FAILED, ASK_FROM_BACKUP, TELL_BACKUP
}
